### PR TITLE
Bartbalaz readme update

### PR DESCRIPTION
**Pull request by bartbalaz**

### CODE REVIEW

**Comment by bartbalaz** [comment]
Please approve this pull request

**Comment by bgrozev** [comment]
Thanks, I added similar text in #35 (I'd have to ask you to sign a CLA otherwise)

**Comment by bartbalaz** [comment]
Hi,

It's ok, let's keep it that way!
For the future, where/how can I sign a CLA? I cannot find any information
on the Jitsi github pages. Is it on per pull-request basis or once per
contributor? Does it have to be signed per sub-project or once for all the
Jitsi projects? I'm asking because we are planning to potentially
contribute to the Jitsi project. Since I will do that under my employer's
(Nuance) responsibility, I will need to get it verified by our legal team.
Not that I expect any issues but I don't want to get into any trouble.
Thanks!

Regards,

/Bartosz

**Comment by bartbalaz** [comment]
Hi,

While waiting for your response I found this information:
https://github.com/jitsi/jitsi/blob/master/CONTRIBUTING.md. Please could
you confirm that this is the right reference. Thank you!

Regards,

/Bartosz

**Pull request closed without merging**
